services:
  mongodb:
    image: mongo:8
    container_name: recipes-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: recipes_db
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
